services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test

  backend:
    build: .
    container_name: dojo_test
    ports:
      - 8089:8089
    environment:
      api-key: 7836fd791123b0cc3a6c0363fd5afdf1
      db-url: jdbc:postgresql://db:5432/test
      db-username: postgres
      db-password: password
    depends_on:
      - db
    restart: always


